// <auto-generated>
//     tools/Generate-Strings.ps1 が Strings.resx から生成している。
//     直接編集しても次の生成で消える。文字列を足すときは resx を直して再生成すること。
// </auto-generated>
#nullable enable
using System.Globalization;
using System.Resources;

namespace Kata.App.Localization;

/// <summary>画面に出す文字列。実際の言語は起動時の CurrentUICulture で決まる。</summary>
public static class Strings
{
    public static ResourceManager ResourceManager { get; } =
        new("Kata.App.Localization.Strings", typeof(Strings).Assembly);

    private static string Get(string key)
        => ResourceManager.GetString(key, CultureInfo.CurrentUICulture) ?? key;

    /// <summary>Kind</summary>
    public static string AddGhostType_Kind => Get("AddGhostType_Kind");

    /// <summary>Namespace</summary>
    public static string AddGhostType_Namespace => Get("AddGhostType_Namespace");

    /// <summary>Add ghost type</summary>
    public static string AddGhostType_Title => Get("AddGhostType_Title");

    /// <summary>Type name</summary>
    public static string AddGhostType_TypeName => Get("AddGhostType_TypeName");

    /// <summary>Default value (optional; recommended to keep call sites compiling)</summary>
    public static string AddParameter_DefaultValue => Get("AddParameter_DefaultValue");

    /// <summary>Add parameter to method</summary>
    public static string AddParameter_Heading => Get("AddParameter_Heading");

    /// <summary>Parameter name</summary>
    public static string AddParameter_Name => Get("AddParameter_Name");

    /// <summary>Add parameter</summary>
    public static string AddParameter_Title => Get("AddParameter_Title");

    /// <summary>Parameter type</summary>
    public static string AddParameter_Type => Get("AddParameter_Type");

    /// <summary>Diff apply failed ({0}): {1}</summary>
    public static string Ai_BuildError_ApplyFailed_Format => Get("Ai_BuildError_ApplyFailed_Format");

    /// <summary>Followup asking for missing .cpp definitions still incomplete.</summary>
    public static string Ai_BuildError_FollowupStillMissing => Get("Ai_BuildError_FollowupStillMissing");

    /// <summary>No applicable changes were produced.</summary>
    public static string Ai_BuildError_NoApplicableChanges => Get("Ai_BuildError_NoApplicableChanges");

    /// <summary>Diff was parsed but no changes were produced ({0}).</summary>
    public static string Ai_BuildError_NoChangesProduced_Format => Get("Ai_BuildError_NoChangesProduced_Format");

    /// <summary>Could not extract a diff block from the AI response.</summary>
    public static string Ai_BuildError_NoDiffBlock => Get("Ai_BuildError_NoDiffBlock");

    /// <summary>No hunks found in the diff block.</summary>
    public static string Ai_BuildError_NoHunks => Get("Ai_BuildError_NoHunks");

    /// <summary>Failed to read original file ({0}): {1}</summary>
    public static string Ai_BuildError_ReadOriginalFailed_Format => Get("Ai_BuildError_ReadOriginalFailed_Format");

    /// <summary>Diff transform threw an exception: {0} — {1}</summary>
    public static string Ai_BuildError_TransformException_Format => Get("Ai_BuildError_TransformException_Format");

    /// <summary>Could not resolve the diff target file: {0}</summary>
    public static string Ai_BuildError_UnknownTargetFile_Format => Get("Ai_BuildError_UnknownTargetFile_Format");

    /// <summary>AI proposal ({0} file change(s))</summary>
    public static string Ai_ChangeSetSummary_Format => Get("Ai_ChangeSetSummary_Format");

    /// <summary>AI proposal ({0}) — {1}: {2}</summary>
    public static string Ai_Rationale_Format => Get("Ai_Rationale_Format");

    /// <summary>({0}/{1})</summary>
    public static string AiQuota_BadgeRemaining_Format => Get("AiQuota_BadgeRemaining_Format");

    /// <summary>You've used all {0} AI consultations available this month in the Community edition. The quota resets on {1:yyyy-MM-dd} (UTC).  Kata Pro gives you unlimited AI consultations, Team Collab features, and priority support.</summary>
    public static string AiQuota_Dialog_Body_Format => Get("AiQuota_Dialog_Body_Format");

    /// <summary>Close</summary>
    public static string AiQuota_Dialog_CloseButton => Get("AiQuota_Dialog_CloseButton");

    /// <summary>I already have a key…</summary>
    public static string AiQuota_Dialog_EnterKeyButton => Get("AiQuota_Dialog_EnterKeyButton");

    /// <summary>AI consultation limit reached</summary>
    public static string AiQuota_Dialog_Heading => Get("AiQuota_Dialog_Heading");

    /// <summary>Buy Kata Pro</summary>
    public static string AiQuota_Dialog_PurchaseButton => Get("AiQuota_Dialog_PurchaseButton");

    /// <summary>You've used all {0} AI consultations available this month in the Community edition.  The quota resets on {1:yyyy-MM-dd} (UTC).  Upgrade to Kata Pro for unlimited AI consultations and additional features (Team Collab, priority support). https://kata.dhq-boiler.dev/pro</summary>
    public static string AiQuota_ExceededMessage_Format => Get("AiQuota_ExceededMessage_Format");

    /// <summary>AI consultation limit reached ({0}/{1} used this month). Upgrade to Pro for unlimited usage.</summary>
    public static string AiQuota_ExceededStatus_Format => Get("AiQuota_ExceededStatus_Format");

    /// <summary>AI consultation limit reached</summary>
    public static string AiQuota_ExceededTitle => Get("AiQuota_ExceededTitle");

    /// <summary>AI consultation ({0}): {1} of {2} remaining this month (Community edition).</summary>
    public static string AiQuota_RemainingStatus_Format => Get("AiQuota_RemainingStatus_Format");

    /// <summary>0s</summary>
    public static string AiRequest_Elapsed_Initial => Get("AiRequest_Elapsed_Initial");

    /// <summary>{0}m {1}s</summary>
    public static string AiRequest_Elapsed_MinutesSeconds_Format => Get("AiRequest_Elapsed_MinutesSeconds_Format");

    /// <summary>{0}s</summary>
    public static string AiRequest_Elapsed_Seconds_Format => Get("AiRequest_Elapsed_Seconds_Format");

    /// <summary>Asking {0} for a refactor proposal…</summary>
    public static string AiRequest_Headline_Format => Get("AiRequest_Headline_Format");

    /// <summary>Backend: {0}   Target: {1}   Type: {2}</summary>
    public static string AiRequest_Subtitle_Format => Get("AiRequest_Subtitle_Format");

    /// <summary>Consulting AI…</summary>
    public static string AiRequest_Title => Get("AiRequest_Title");

    /// <summary>Consolidate conditional expression</summary>
    public static string CodeMenu_ConsolidateConditional => Get("CodeMenu_ConsolidateConditional");

    /// <summary>Consolidate duplicate conditional fragments</summary>
    public static string CodeMenu_ConsolidateDuplicateFragments => Get("CodeMenu_ConsolidateDuplicateFragments");

    /// <summary>Decompose conditional…</summary>
    public static string CodeMenu_DecomposeConditional => Get("CodeMenu_DecomposeConditional");

    /// <summary>Extract method…</summary>
    public static string CodeMenu_ExtractMethod => Get("CodeMenu_ExtractMethod");

    /// <summary>Extract variable…</summary>
    public static string CodeMenu_ExtractVariable => Get("CodeMenu_ExtractVariable");

    /// <summary>Replace nested conditional with guard clauses</summary>
    public static string CodeMenu_GuardClauses => Get("CodeMenu_GuardClauses");

    /// <summary>Inline method</summary>
    public static string CodeMenu_InlineMethod => Get("CodeMenu_InlineMethod");

    /// <summary>Inline variable</summary>
    public static string CodeMenu_InlineVariable => Get("CodeMenu_InlineVariable");

    /// <summary>Introduce assertion…</summary>
    public static string CodeMenu_IntroduceAssertion => Get("CodeMenu_IntroduceAssertion");

    /// <summary>Find refs</summary>
    public static string CodeViewer_FindRefs => Get("CodeViewer_FindRefs");

    /// <summary>Find all references to the currently viewed member</summary>
    public static string CodeViewer_FindRefs_Tooltip => Get("CodeViewer_FindRefs_Tooltip");

    /// <summary>Selection:</summary>
    public static string CodeViewer_Selection => Get("CodeViewer_Selection");

    /// <summary>Cancel</summary>
    public static string Common_Cancel => Get("Common_Cancel");

    /// <summary>OK</summary>
    public static string Common_Ok => Get("Common_Ok");

    /// <summary>Collapse '{0}' into its base '{1}'?  All members of '{0}' will be moved into the base, then '{0}' will be deleted and every usage rewritten to the base.</summary>
    public static string Confirm_CollapseHierarchy_Body => Get("Confirm_CollapseHierarchy_Body");

    /// <summary>Collapse hierarchy</summary>
    public static string Confirm_CollapseHierarchy_Caption => Get("Confirm_CollapseHierarchy_Caption");

    /// <summary>Move the body of {0}'s constructor into {1}'s constructor?  {0}'s constructor will become empty and delegate via `: base()`.</summary>
    public static string Confirm_PullUpCtor_Body => Get("Confirm_PullUpCtor_Body");

    /// <summary>Pull up constructor body</summary>
    public static string Confirm_PullUpCtor_Caption => Get("Confirm_PullUpCtor_Caption");

    /// <summary>Make {0} effectively immutable? All mutable fields will get 'readonly' and property setters become 'init'.</summary>
    public static string Confirm_RefToValue_Body => Get("Confirm_RefToValue_Body");

    /// <summary>Change reference to value</summary>
    public static string Confirm_RefToValue_Caption => Get("Confirm_RefToValue_Caption");

    /// <summary>Remove subclass '{0}' and rewrite every usage to its base type '{1}'?  The declaration file will be deleted. This cannot be undone from within Kata (use git).</summary>
    public static string Confirm_RemoveSubclass_Body => Get("Confirm_RemoveSubclass_Body");

    /// <summary>Remove subclass</summary>
    public static string Confirm_RemoveSubclass_Caption => Get("Confirm_RemoveSubclass_Caption");

    /// <summary>Add a public static Create factory to {0} and make the existing constructor private?</summary>
    public static string Confirm_ReplaceCtorFactory_Body => Get("Confirm_ReplaceCtorFactory_Body");

    /// <summary>Replace constructor with factory</summary>
    public static string Confirm_ReplaceCtorFactory_Caption => Get("Confirm_ReplaceCtorFactory_Caption");

    /// <summary>Drop 'abstract' from {0} and delete these subclass file(s)?  {1}  Pull up any subclass-specific behaviour BEFORE running this.</summary>
    public static string Confirm_ReplaceSubclassFields_Body => Get("Confirm_ReplaceSubclassFields_Body");

    /// <summary>Replace subclass with fields</summary>
    public static string Confirm_ReplaceSubclassFields_Caption => Get("Confirm_ReplaceSubclassFields_Caption");

    /// <summary>Add a static Dictionary&lt;string, {0}&gt; registry and a GetOrCreate factory on {0}?</summary>
    public static string Confirm_ValueToRef_Body => Get("Confirm_ValueToRef_Body");

    /// <summary>Change value to reference</summary>
    public static string Confirm_ValueToRef_Caption => Get("Confirm_ValueToRef_Caption");

    /// <summary>Data record type (destination — must appear as first parameter)</summary>
    public static string ConvertProceduralToObjects_DataRecord => Get("ConvertProceduralToObjects_DataRecord");

    /// <summary>Methods to move (checked = qualifying methods only)</summary>
    public static string ConvertProceduralToObjects_MethodsToMove => Get("ConvertProceduralToObjects_MethodsToMove");

    /// <summary>Procedural class (static procedures will be moved)</summary>
    public static string ConvertProceduralToObjects_ProceduralClass => Get("ConvertProceduralToObjects_ProceduralClass");

    /// <summary>Silently skipped if first param type doesn't match the record above.</summary>
    public static string ConvertProceduralToObjects_SkipHint => Get("ConvertProceduralToObjects_SkipHint");

    /// <summary>Convert procedural to objects</summary>
    public static string ConvertProceduralToObjects_Title => Get("ConvertProceduralToObjects_Title");

    /// <summary>Condition method (returns bool)</summary>
    public static string DecomposeConditional_ConditionMethod => Get("DecomposeConditional_ConditionMethod");

    /// <summary>Else method (void, blank if no else)</summary>
    public static string DecomposeConditional_ElseMethod => Get("DecomposeConditional_ElseMethod");

    /// <summary>Then method (void)</summary>
    public static string DecomposeConditional_ThenMethod => Get("DecomposeConditional_ThenMethod");

    /// <summary>Decompose conditional</summary>
    public static string DecomposeConditional_Title => Get("DecomposeConditional_Title");

    /// <summary>AI analysis ({0}) — {1}</summary>
    public static string Dialog_Ai_AnalysisCaption_Format => Get("Dialog_Ai_AnalysisCaption_Format");

    /// <summary>AI proposal diff extraction failed ({0}) — {1}</summary>
    public static string Dialog_Ai_DiffExtractFailedCaption_Format => Get("Dialog_Ai_DiffExtractFailedCaption_Format");

    /// <summary>(empty response)</summary>
    public static string Dialog_Ai_EmptyResponseBody => Get("Dialog_Ai_EmptyResponseBody");

    /// <summary>Containing member</summary>
    public static string Dialog_ContainingMember => Get("Dialog_ContainingMember");

    /// <summary>Members</summary>
    public static string Dialog_Members => Get("Dialog_Members");

    /// <summary>Method</summary>
    public static string Dialog_Method => Get("Dialog_Method");

    /// <summary>New class name</summary>
    public static string Dialog_NewClassName => Get("Dialog_NewClassName");

    /// <summary>New name</summary>
    public static string Dialog_NewName => Get("Dialog_NewName");

    /// <summary>Owner class</summary>
    public static string Dialog_OwnerClass => Get("Dialog_OwnerClass");

    /// <summary>Preview</summary>
    public static string Dialog_Preview => Get("Dialog_Preview");

    /// <summary>Select all</summary>
    public static string Dialog_SelectAll => Get("Dialog_SelectAll");

    /// <summary>Source class</summary>
    public static string Dialog_SourceClass => Get("Dialog_SourceClass");

    /// <summary>Diff: +{0} added / -{1} removed / ~{2} modified</summary>
    public static string DiffOverlay_Summary => Get("DiffOverlay_Summary");

    /// <summary>Apply</summary>
    public static string DiffPreview_Apply => Get("DiffPreview_Apply");

    /// <summary>Failed to write instruction: {0}</summary>
    public static string DiffPreview_ExportFailure_Body => Get("DiffPreview_ExportFailure_Body");

    /// <summary>Export failed</summary>
    public static string DiffPreview_ExportFailure_Caption => Get("DiffPreview_ExportFailure_Caption");

    /// <summary>Export instruction…</summary>
    public static string DiffPreview_ExportInstruction => Get("DiffPreview_ExportInstruction");

    /// <summary>Instruction written to: {0}</summary>
    public static string DiffPreview_ExportSuccess_Body => Get("DiffPreview_ExportSuccess_Body");

    /// <summary>Export instruction</summary>
    public static string DiffPreview_ExportSuccess_Caption => Get("DiffPreview_ExportSuccess_Caption");

    /// <summary>Reject</summary>
    public static string DiffPreview_Reject => Get("DiffPreview_Reject");

    /// <summary>Preview changes</summary>
    public static string DiffPreview_Title => Get("DiffPreview_Title");

    /// <summary>Unified diff (±3 lines context)</summary>
    public static string DiffPreview_UnifiedDiff => Get("DiffPreview_UnifiedDiff");

    /// <summary>Change bidirectional to unidirectional</summary>
    public static string DropBackReference_Heading => Get("DropBackReference_Heading");

    /// <summary>Pick a field or property to drop (the other class keeps its side)</summary>
    public static string DropBackReference_Hint => Get("DropBackReference_Hint");

    /// <summary>Drop back-reference</summary>
    public static string DropBackReference_Title => Get("DropBackReference_Title");

    /// <summary>Pick a field to convert into an auto-property</summary>
    public static string EncapsulateField_Hint => Get("EncapsulateField_Hint");

    /// <summary>Encapsulate field</summary>
    public static string EncapsulateField_Title => Get("EncapsulateField_Title");

    /// <summary>Delegate property name (on source class)</summary>
    public static string ExtractClass_DelegatePropName => Get("ExtractClass_DelegatePropName");

    /// <summary>Members to move out</summary>
    public static string ExtractClass_MembersToMove => Get("ExtractClass_MembersToMove");

    /// <summary>Extract class / Separate domain from presentation</summary>
    public static string ExtractClass_Title => Get("ExtractClass_Title");

    /// <summary>Extract hierarchy</summary>
    public static string ExtractHierarchy_Heading => Get("ExtractHierarchy_Heading");

    /// <summary>Leave everything unchecked to just scaffold empty subclasses.</summary>
    public static string ExtractHierarchy_LeaveUncheckedHint => Get("ExtractHierarchy_LeaveUncheckedHint");

    /// <summary>Methods to virtualize (checked → made abstract on owner + override stub in each subclass)</summary>
    public static string ExtractHierarchy_MethodsToVirtualize => Get("ExtractHierarchy_MethodsToVirtualize");

    /// <summary>Owner class (will become abstract)</summary>
    public static string ExtractHierarchy_OwnerClassAbstract => Get("ExtractHierarchy_OwnerClassAbstract");

    /// <summary>Subclass names (comma-separated, one per case)</summary>
    public static string ExtractHierarchy_SubclassNames => Get("ExtractHierarchy_SubclassNames");

    /// <summary>Extract hierarchy / Replace conditional with polymorphism</summary>
    public static string ExtractHierarchy_Title => Get("ExtractHierarchy_Title");

    /// <summary>New interface name</summary>
    public static string ExtractInterface_NewName => Get("ExtractInterface_NewName");

    /// <summary>Extract interface</summary>
    public static string ExtractInterface_Title => Get("ExtractInterface_Title");

    /// <summary>New method name</summary>
    public static string ExtractMethod_NewName => Get("ExtractMethod_NewName");

    /// <summary>Extract method</summary>
    public static string ExtractMethod_Title => Get("ExtractMethod_Title");

    /// <summary>Members to move up</summary>
    public static string ExtractSuperclass_MembersToMoveUp => Get("ExtractSuperclass_MembersToMoveUp");

    /// <summary>New superclass name</summary>
    public static string ExtractSuperclass_NewName => Get("ExtractSuperclass_NewName");

    /// <summary>Extract superclass</summary>
    public static string ExtractSuperclass_Title => Get("ExtractSuperclass_Title");

    /// <summary>New variable name</summary>
    public static string ExtractVariable_NewName => Get("ExtractVariable_NewName");

    /// <summary>Extract variable</summary>
    public static string ExtractVariable_Title => Get("ExtractVariable_Title");

    /// <summary>Impact focus: {0} seed(s), {1} reached ({2} user, {3} external, {4} filtered-out, {5} missing) within {6} hop(s) — [{7}]</summary>
    public static string ImpactFocus_Summary => Get("ImpactFocus_Summary");

    /// <summary>Condition (must be true)</summary>
    public static string IntroduceAssertion_Condition => Get("IntroduceAssertion_Condition");

    /// <summary>Message (optional — defaults to the condition text)</summary>
    public static string IntroduceAssertion_Message => Get("IntroduceAssertion_Message");

    /// <summary>Introduce assertion</summary>
    public static string IntroduceAssertion_Title => Get("IntroduceAssertion_Title");

    /// <summary>New parameter-object class name</summary>
    public static string IntroduceParameterObject_NewClassName => Get("IntroduceParameterObject_NewClassName");

    /// <summary>Parameter name inside the method</summary>
    public static string IntroduceParameterObject_ParamName => Get("IntroduceParameterObject_ParamName");

    /// <summary>Introduce parameter object</summary>
    public static string IntroduceParameterObject_Title => Get("IntroduceParameterObject_Title");

    /// <summary>Starting…</summary>
    public static string Loading_PhaseStarting => Get("Loading_PhaseStarting");

    /// <summary>Roslyn is opening the solution — the mouse cursor may stall briefly.</summary>
    public static string Loading_RoslynHint => Get("Loading_RoslynHint");

    /// <summary>Parsing C++/CLI headers…</summary>
    public static string LoadPhase_CppCompile => Get("LoadPhase_CppCompile");

    /// <summary>Discovering foreign projects…</summary>
    public static string LoadPhase_Discover => Get("LoadPhase_Discover");

    /// <summary>Applying filters…</summary>
    public static string LoadPhase_Filter => Get("LoadPhase_Filter");

    /// <summary>Building foreign-project models…</summary>
    public static string LoadPhase_ForeignProjects => Get("LoadPhase_ForeignProjects");

    /// <summary>Building the type graph…</summary>
    public static string LoadPhase_Graph => Get("LoadPhase_Graph");

    /// <summary>Injecting Cpp shim references…</summary>
    public static string LoadPhase_InjectShim => Get("LoadPhase_InjectShim");

    /// <summary>Running Sugiyama layout…</summary>
    public static string LoadPhase_Layout => Get("LoadPhase_Layout");

    /// <summary>Mapping symbols to the Kata model…</summary>
    public static string LoadPhase_MapAsync => Get("LoadPhase_MapAsync");

    /// <summary>Opening the solution (Roslyn / MSBuild)…</summary>
    public static string LoadPhase_OpenSln => Get("LoadPhase_OpenSln");

    /// <summary>_Edit</summary>
    public static string Menu_Edit => Get("Menu_Edit");

    /// <summary>Clear _Filter</summary>
    public static string Menu_Edit_ClearFilter => Get("Menu_Edit_ClearFilter");

    /// <summary>Clear _Focus</summary>
    public static string Menu_Edit_ClearFocus => Get("Menu_Edit_ClearFocus");

    /// <summary>_File</summary>
    public static string Menu_File => Get("Menu_File");

    /// <summary>E_xit</summary>
    public static string Menu_File_Exit => Get("Menu_File_Exit");

    /// <summary>_Open Solution…</summary>
    public static string Menu_File_OpenSolution => Get("Menu_File_OpenSolution");

    /// <summary>_Preferences…</summary>
    public static string Menu_File_Preferences => Get("Menu_File_Preferences");

    /// <summary>_Help</summary>
    public static string Menu_Help => Get("Menu_Help");

    /// <summary>_Refactor</summary>
    public static string Menu_Refactor => Get("Menu_Refactor");

    /// <summary>_Add Ghost Type…</summary>
    public static string Menu_Refactor_AddGhostType => Get("Menu_Refactor_AddGhostType");

    /// <summary>Extract _Class…</summary>
    public static string Menu_Refactor_ExtractClass => Get("Menu_Refactor_ExtractClass");

    /// <summary>Extract _Interface…</summary>
    public static string Menu_Refactor_ExtractInterface => Get("Menu_Refactor_ExtractInterface");

    /// <summary>Extract Super_class…</summary>
    public static string Menu_Refactor_ExtractSuperclass => Get("Menu_Refactor_ExtractSuperclass");

    /// <summary>_Rename…</summary>
    public static string Menu_Refactor_Rename => Get("Menu_Refactor_Rename");

    /// <summary>_Tools</summary>
    public static string Menu_Tools => Get("Menu_Tools");

    /// <summary>_View</summary>
    public static string Menu_View => Get("Menu_View");

    /// <summary>Clear _Diff Overlay</summary>
    public static string Menu_View_ClearDiffOverlay => Get("Menu_View_ClearDiffOverlay");

    /// <summary>Clear _Impact Focus</summary>
    public static string Menu_View_ClearImpactFocus => Get("Menu_View_ClearImpactFocus");

    /// <summary>E_xpand Impact Focus</summary>
    public static string Menu_View_ExpandImpactFocus => Get("Menu_View_ExpandImpactFocus");

    /// <summary>From class</summary>
    public static string MoveMember_FromClass => Get("MoveMember_FromClass");

    /// <summary>Move members</summary>
    public static string MoveMember_Title => Get("MoveMember_Title");

    /// <summary>To class</summary>
    public static string MoveMember_ToClass => Get("MoveMember_ToClass");

    /// <summary>Add parameter…</summary>
    public static string NodeMenu_AddParameter => Get("NodeMenu_AddParameter");

    /// <summary>Change reference to value…</summary>
    public static string NodeMenu_ChangeReferenceToValue => Get("NodeMenu_ChangeReferenceToValue");

    /// <summary>Change value to reference…</summary>
    public static string NodeMenu_ChangeValueToReference => Get("NodeMenu_ChangeValueToReference");

    /// <summary>Collapse into base…</summary>
    public static string NodeMenu_CollapseIntoBase => Get("NodeMenu_CollapseIntoBase");

    /// <summary>Convert procedural to objects…</summary>
    public static string NodeMenu_ConvertProceduralToObjects => Get("NodeMenu_ConvertProceduralToObjects");

    /// <summary>Drop back-reference…</summary>
    public static string NodeMenu_DropBackReference => Get("NodeMenu_DropBackReference");

    /// <summary>Encapsulate field…</summary>
    public static string NodeMenu_EncapsulateField => Get("NodeMenu_EncapsulateField");

    /// <summary>Extract class / Separate domain from presentation…</summary>
    public static string NodeMenu_ExtractClass => Get("NodeMenu_ExtractClass");

    /// <summary>Extract hierarchy / Replace conditional with polymorphism…</summary>
    public static string NodeMenu_ExtractHierarchy => Get("NodeMenu_ExtractHierarchy");

    /// <summary>Extract interface…</summary>
    public static string NodeMenu_ExtractInterface => Get("NodeMenu_ExtractInterface");

    /// <summary>Extract superclass…</summary>
    public static string NodeMenu_ExtractSuperclass => Get("NodeMenu_ExtractSuperclass");

    /// <summary>Focus impact from here (1 hop)</summary>
    public static string NodeMenu_FocusImpactOneHop => Get("NodeMenu_FocusImpactOneHop");

    /// <summary>Introduce Null Object…</summary>
    public static string NodeMenu_IntroduceNullObject => Get("NodeMenu_IntroduceNullObject");

    /// <summary>Introduce parameter object…</summary>
    public static string NodeMenu_IntroduceParameterObject => Get("NodeMenu_IntroduceParameterObject");

    /// <summary>Move field…</summary>
    public static string NodeMenu_MoveField => Get("NodeMenu_MoveField");

    /// <summary>Move method…</summary>
    public static string NodeMenu_MoveMethod => Get("NodeMenu_MoveMethod");

    /// <summary>Preserve whole object…</summary>
    public static string NodeMenu_PreserveWholeObject => Get("NodeMenu_PreserveWholeObject");

    /// <summary>Pull up constructor body…</summary>
    public static string NodeMenu_PullUpConstructorBody => Get("NodeMenu_PullUpConstructorBody");

    /// <summary>Pull up field…</summary>
    public static string NodeMenu_PullUpField => Get("NodeMenu_PullUpField");

    /// <summary>Pull up method…</summary>
    public static string NodeMenu_PullUpMethod => Get("NodeMenu_PullUpMethod");

    /// <summary>Push down field…</summary>
    public static string NodeMenu_PushDownField => Get("NodeMenu_PushDownField");

    /// <summary>Push down method…</summary>
    public static string NodeMenu_PushDownMethod => Get("NodeMenu_PushDownMethod");

    /// <summary>Remove parameter…</summary>
    public static string NodeMenu_RemoveParameter => Get("NodeMenu_RemoveParameter");

    /// <summary>Remove setting method…</summary>
    public static string NodeMenu_RemoveSettingMethod => Get("NodeMenu_RemoveSettingMethod");

    /// <summary>Remove subclass…</summary>
    public static string NodeMenu_RemoveSubclass => Get("NodeMenu_RemoveSubclass");

    /// <summary>Rename…</summary>
    public static string NodeMenu_Rename => Get("NodeMenu_Rename");

    /// <summary>Rename field…</summary>
    public static string NodeMenu_RenameField => Get("NodeMenu_RenameField");

    /// <summary>Rename member…</summary>
    public static string NodeMenu_RenameMember => Get("NodeMenu_RenameMember");

    /// <summary>Rename parameter…</summary>
    public static string NodeMenu_RenameParameter => Get("NodeMenu_RenameParameter");

    /// <summary>Replace array with object…</summary>
    public static string NodeMenu_ReplaceArrayWithObject => Get("NodeMenu_ReplaceArrayWithObject");

    /// <summary>Replace constructor with factory…</summary>
    public static string NodeMenu_ReplaceConstructorWithFactory => Get("NodeMenu_ReplaceConstructorWithFactory");

    /// <summary>Replace data value with object…</summary>
    public static string NodeMenu_ReplaceDataValueWithObject => Get("NodeMenu_ReplaceDataValueWithObject");

    /// <summary>Replace magic number…</summary>
    public static string NodeMenu_ReplaceMagicNumber => Get("NodeMenu_ReplaceMagicNumber");

    /// <summary>Replace subclass hierarchy with fields…</summary>
    public static string NodeMenu_ReplaceSubclassWithFields => Get("NodeMenu_ReplaceSubclassWithFields");

    /// <summary>Replace type code with class…</summary>
    public static string NodeMenu_ReplaceTypeCodeWithClass => Get("NodeMenu_ReplaceTypeCodeWithClass");

    /// <summary>Replace type code with subclasses…</summary>
    public static string NodeMenu_ReplaceTypeCodeWithSubclasses => Get("NodeMenu_ReplaceTypeCodeWithSubclasses");

    /// <summary>Self encapsulate field…</summary>
    public static string NodeMenu_SelfEncapsulateField => Get("NodeMenu_SelfEncapsulateField");

    /// <summary>Tease apart inheritance…</summary>
    public static string NodeMenu_TeaseApartInheritance => Get("NodeMenu_TeaseApartInheritance");

    /// <summary>Claude model identifier</summary>
    public static string Preferences_Ai_ClaudeModel_Label => Get("Preferences_Ai_ClaudeModel_Label");

    /// <summary>Codex model identifier</summary>
    public static string Preferences_Ai_CodexModel_Label => Get("Preferences_Ai_CodexModel_Label");

    /// <summary>The dropdown lists known model IDs. Leave blank to use each CLI's default model. New models can be typed in directly — updates to Kata add the latest IDs to this list.</summary>
    public static string Preferences_Ai_ModelHint => Get("Preferences_Ai_ModelHint");

    /// <summary>AI</summary>
    public static string Preferences_Category_Ai => Get("Preferences_Category_Ai");

    /// <summary>Diagnostics</summary>
    public static string Preferences_Category_Diagnostics => Get("Preferences_Category_Diagnostics");

    /// <summary>General</summary>
    public static string Preferences_Category_General => Get("Preferences_Category_General");

    /// <summary>Pro License</summary>
    public static string Preferences_Category_Pro => Get("Preferences_Category_Pro");

    /// <summary>Enable diagnostic mode (log apply / diff overlay events to the file below)</summary>
    public static string Preferences_Diagnostics_Enabled_Label => Get("Preferences_Diagnostics_Enabled_Label");

    /// <summary>When on, each refactor apply appends a timestamped trace to the log file (change list, before/after type count, safety-net trigger, SolutionDiffer output, per-member overlay hit/miss). Off by default; turn on only while investigating a bug.</summary>
    public static string Preferences_Diagnostics_Hint => Get("Preferences_Diagnostics_Hint");

    /// <summary>Windows already open keep their current language. New windows use the new one.</summary>
    public static string Preferences_Language_Hint => Get("Preferences_Language_Hint");

    /// <summary>Language</summary>
    public static string Preferences_Language_Label => Get("Preferences_Language_Label");

    /// <summary>Follow OS setting</summary>
    public static string Preferences_Language_System => Get("Preferences_Language_System");

    /// <summary>Deactivate license</summary>
    public static string Preferences_Pro_Deactivate => Get("Preferences_Pro_Deactivate");

    /// <summary>This will release the current activation on the Lemon Squeezy server so you can activate the key on another machine. You'll need to re-enter the key and restart Kata to activate again on this machine.</summary>
    public static string Preferences_Pro_Deactivate_ConfirmBody => Get("Preferences_Pro_Deactivate_ConfirmBody");

    /// <summary>Deactivate this license?</summary>
    public static string Preferences_Pro_Deactivate_ConfirmTitle => Get("Preferences_Pro_Deactivate_ConfirmTitle");

    /// <summary>Deactivation failed.</summary>
    public static string Preferences_Pro_Deactivate_Failed => Get("Preferences_Pro_Deactivate_Failed");

    /// <summary>License deactivated. Restart Kata to apply.</summary>
    public static string Preferences_Pro_Deactivated_Restart => Get("Preferences_Pro_Deactivated_Restart");

    /// <summary>Deactivating…</summary>
    public static string Preferences_Pro_Deactivating => Get("Preferences_Pro_Deactivating");

    /// <summary>Email:</summary>
    public static string Preferences_Pro_EmailLabel => Get("Preferences_Pro_EmailLabel");

    /// <summary>Expires:</summary>
    public static string Preferences_Pro_ExpiresLabel => Get("Preferences_Pro_ExpiresLabel");

    /// <summary>Perpetual (buyout)</summary>
    public static string Preferences_Pro_ExpiresPerpetual => Get("Preferences_Pro_ExpiresPerpetual");

    /// <summary>Enter the license key you received when purchasing Kata Pro. Purchase at https://kata.dhq-boiler.dev/pro</summary>
    public static string Preferences_Pro_Hint => Get("Preferences_Pro_Hint");

    /// <summary>License key:</summary>
    public static string Preferences_Pro_LicenseKeyLabel => Get("Preferences_Pro_LicenseKeyLabel");

    /// <summary>Restart Kata for license changes to take effect.</summary>
    public static string Preferences_Pro_RestartHint => Get("Preferences_Pro_RestartHint");

    /// <summary>Pro — {0}</summary>
    public static string Preferences_Pro_Status_Active_Format => Get("Preferences_Pro_Status_Active_Format");

    /// <summary>Community edition</summary>
    public static string Preferences_Pro_Status_Community => Get("Preferences_Pro_Status_Community");

    /// <summary>License expired</summary>
    public static string Preferences_Pro_Status_Expired => Get("Preferences_Pro_Status_Expired");

    /// <summary>License key invalid</summary>
    public static string Preferences_Pro_Status_Invalid => Get("Preferences_Pro_Status_Invalid");

    /// <summary>Current status:</summary>
    public static string Preferences_Pro_StatusLabel => Get("Preferences_Pro_StatusLabel");

    /// <summary>Preferences</summary>
    public static string Preferences_Title => Get("Preferences_Title");

    /// <summary>Existing parameter names to fold in (comma-separated)</summary>
    public static string PreserveWholeObject_FoldIn => Get("PreserveWholeObject_FoldIn");

    /// <summary>New parameter name</summary>
    public static string PreserveWholeObject_NewParamName => Get("PreserveWholeObject_NewParamName");

    /// <summary>Preserve whole object</summary>
    public static string PreserveWholeObject_Title => Get("PreserveWholeObject_Title");

    /// <summary>Whole-object type</summary>
    public static string PreserveWholeObject_WholeObjType => Get("PreserveWholeObject_WholeObjType");

    /// <summary>From subclass</summary>
    public static string PullUpMember_FromSubclass => Get("PullUpMember_FromSubclass");

    /// <summary>Pull up members</summary>
    public static string PullUpMember_Title => Get("PullUpMember_Title");

    /// <summary>Up to parent</summary>
    public static string PullUpMember_UpToParent => Get("PullUpMember_UpToParent");

    /// <summary>Down to subclass</summary>
    public static string PushDownMember_DownToSubclass => Get("PushDownMember_DownToSubclass");

    /// <summary>From parent</summary>
    public static string PushDownMember_FromParent => Get("PushDownMember_FromParent");

    /// <summary>Push down members</summary>
    public static string PushDownMember_Title => Get("PushDownMember_Title");

    /// <summary>{0} reference(s) to {1}.{2}</summary>
    public static string Refs_CountFound => Get("Refs_CountFound");

    /// <summary>Find references failed: {0}</summary>
    public static string Refs_FindFailed => Get("Refs_FindFailed");

    /// <summary>Searching references for {0}.{1}…</summary>
    public static string Refs_SearchingFor => Get("Refs_SearchingFor");

    /// <summary>Remove parameter from method</summary>
    public static string RemoveParameter_Heading => Get("RemoveParameter_Heading");

    /// <summary>Parameter name to remove</summary>
    public static string RemoveParameter_Name => Get("RemoveParameter_Name");

    /// <summary>Remove parameter</summary>
    public static string RemoveParameter_Title => Get("RemoveParameter_Title");

    /// <summary>Pick a property (or setter method) to make read-only</summary>
    public static string RemoveSettingMethod_Hint => Get("RemoveSettingMethod_Hint");

    /// <summary>Remove setting method</summary>
    public static string RemoveSettingMethod_Title => Get("RemoveSettingMethod_Title");

    /// <summary>Current name</summary>
    public static string Rename_CurrentName => Get("Rename_CurrentName");

    /// <summary>Rename</summary>
    public static string Rename_Title => Get("Rename_Title");

    /// <summary>Field</summary>
    public static string RenameField_Field => Get("RenameField_Field");

    /// <summary>Rename field</summary>
    public static string RenameField_Title => Get("RenameField_Title");

    /// <summary>Member (method / property / field / event)</summary>
    public static string RenameMember_MemberHint => Get("RenameMember_MemberHint");

    /// <summary>Rename member</summary>
    public static string RenameMember_Title => Get("RenameMember_Title");

    /// <summary>New parameter name</summary>
    public static string RenameParameter_NewName => Get("RenameParameter_NewName");

    /// <summary>Old parameter name</summary>
    public static string RenameParameter_OldName => Get("RenameParameter_OldName");

    /// <summary>Rename parameter</summary>
    public static string RenameParameter_Title => Get("RenameParameter_Title");

    /// <summary>Array field / property</summary>
    public static string ReplaceArrayWithObject_ArrayField => Get("ReplaceArrayWithObject_ArrayField");

    /// <summary>Index → field mappings (one per line, 'index:fieldName:fieldType')</summary>
    public static string ReplaceArrayWithObject_IndexMapping => Get("ReplaceArrayWithObject_IndexMapping");

    /// <summary>Replace array with object</summary>
    public static string ReplaceArrayWithObject_Title => Get("ReplaceArrayWithObject_Title");

    /// <summary>Inner property name (default 'Value')</summary>
    public static string ReplaceDataValue_InnerPropName => Get("ReplaceDataValue_InnerPropName");

    /// <summary>Primitive field or property to wrap</summary>
    public static string ReplaceDataValue_PrimitiveField => Get("ReplaceDataValue_PrimitiveField");

    /// <summary>Replace data value with object</summary>
    public static string ReplaceDataValue_Title => Get("ReplaceDataValue_Title");

    /// <summary>Wrapper class name</summary>
    public static string ReplaceDataValue_WrapperClassName => Get("ReplaceDataValue_WrapperClassName");

    /// <summary>Constant name</summary>
    public static string ReplaceMagicNumber_ConstName => Get("ReplaceMagicNumber_ConstName");

    /// <summary>Constant type (e.g. 'int', 'double', 'decimal')</summary>
    public static string ReplaceMagicNumber_ConstType => Get("ReplaceMagicNumber_ConstType");

    /// <summary>Replace magic number with symbolic constant</summary>
    public static string ReplaceMagicNumber_Heading => Get("ReplaceMagicNumber_Heading");

    /// <summary>Literal value (must match source text exactly, e.g. '3.14159', '100', '0.1m')</summary>
    public static string ReplaceMagicNumber_Literal => Get("ReplaceMagicNumber_Literal");

    /// <summary>Replace magic number</summary>
    public static string ReplaceMagicNumber_Title => Get("ReplaceMagicNumber_Title");

    /// <summary>Codes (one per line, 'Name=Value')</summary>
    public static string ReplaceTypeCode_Codes => Get("ReplaceTypeCode_Codes");

    /// <summary>Inner code type (default 'int')</summary>
    public static string ReplaceTypeCode_InnerCodeType => Get("ReplaceTypeCode_InnerCodeType");

    /// <summary>Replace type code with class</summary>
    public static string ReplaceTypeCode_Title => Get("ReplaceTypeCode_Title");

    /// <summary>Type-code field/property</summary>
    public static string ReplaceTypeCode_TypeCodeField => Get("ReplaceTypeCode_TypeCodeField");

    /// <summary>Subclass names (comma-separated, one per code)</summary>
    public static string ReplaceTypeCodeWithSubclasses_SubclassNames => Get("ReplaceTypeCodeWithSubclasses_SubclassNames");

    /// <summary>Replace type code with subclasses</summary>
    public static string ReplaceTypeCodeWithSubclasses_Title => Get("ReplaceTypeCodeWithSubclasses_Title");

    /// <summary>Pick a field — the class will get a matching property and internal refs will be rewritten to use it.</summary>
    public static string SelfEncapsulateField_Hint => Get("SelfEncapsulateField_Hint");

    /// <summary>Self encapsulate field</summary>
    public static string SelfEncapsulateField_Title => Get("SelfEncapsulateField_Title");

    /// <summary>Alternative Classes with Different Interfaces</summary>
    public static string Smell_Category_AlternativeClassesWithDifferentInterfaces => Get("Smell_Category_AlternativeClassesWithDifferentInterfaces");

    /// <summary>Comments</summary>
    public static string Smell_Category_Comments => Get("Smell_Category_Comments");

    /// <summary>Data Class</summary>
    public static string Smell_Category_DataClass => Get("Smell_Category_DataClass");

    /// <summary>Data Clumps</summary>
    public static string Smell_Category_DataClumps => Get("Smell_Category_DataClumps");

    /// <summary>Divergent Change</summary>
    public static string Smell_Category_DivergentChange => Get("Smell_Category_DivergentChange");

    /// <summary>Duplicated Code</summary>
    public static string Smell_Category_DuplicatedCode => Get("Smell_Category_DuplicatedCode");

    /// <summary>Feature Envy</summary>
    public static string Smell_Category_FeatureEnvy => Get("Smell_Category_FeatureEnvy");

    /// <summary>Global Data</summary>
    public static string Smell_Category_GlobalData => Get("Smell_Category_GlobalData");

    /// <summary>Insider Trading</summary>
    public static string Smell_Category_InsiderTrading => Get("Smell_Category_InsiderTrading");

    /// <summary>Large Class</summary>
    public static string Smell_Category_LargeClass => Get("Smell_Category_LargeClass");

    /// <summary>Lazy Element</summary>
    public static string Smell_Category_LazyElement => Get("Smell_Category_LazyElement");

    /// <summary>Long Function</summary>
    public static string Smell_Category_LongFunction => Get("Smell_Category_LongFunction");

    /// <summary>Long Parameter List</summary>
    public static string Smell_Category_LongParameterList => Get("Smell_Category_LongParameterList");

    /// <summary>Loops</summary>
    public static string Smell_Category_Loops => Get("Smell_Category_Loops");

    /// <summary>Message Chains</summary>
    public static string Smell_Category_MessageChains => Get("Smell_Category_MessageChains");

    /// <summary>Middle Man</summary>
    public static string Smell_Category_MiddleMan => Get("Smell_Category_MiddleMan");

    /// <summary>Mutable Data</summary>
    public static string Smell_Category_MutableData => Get("Smell_Category_MutableData");

    /// <summary>Mysterious Name</summary>
    public static string Smell_Category_MysteriousName => Get("Smell_Category_MysteriousName");

    /// <summary>Primitive Obsession</summary>
    public static string Smell_Category_PrimitiveObsession => Get("Smell_Category_PrimitiveObsession");

    /// <summary>Refused Bequest</summary>
    public static string Smell_Category_RefusedBequest => Get("Smell_Category_RefusedBequest");

    /// <summary>Repeated Switches</summary>
    public static string Smell_Category_RepeatedSwitches => Get("Smell_Category_RepeatedSwitches");

    /// <summary>Shotgun Surgery</summary>
    public static string Smell_Category_ShotgunSurgery => Get("Smell_Category_ShotgunSurgery");

    /// <summary>Speculative Generality</summary>
    public static string Smell_Category_SpeculativeGenerality => Get("Smell_Category_SpeculativeGenerality");

    /// <summary>Temporary Field</summary>
    public static string Smell_Category_TemporaryField => Get("Smell_Category_TemporaryField");

    /// <summary>Collapse Hierarchy</summary>
    public static string Smell_Fix_CollapseHierarchy => Get("Smell_Fix_CollapseHierarchy");

    /// <summary>Encapsulate Field</summary>
    public static string Smell_Fix_EncapsulateField => Get("Smell_Fix_EncapsulateField");

    /// <summary>Extract Class</summary>
    public static string Smell_Fix_ExtractClass => Get("Smell_Fix_ExtractClass");

    /// <summary>Extract Superclass</summary>
    public static string Smell_Fix_ExtractSuperclass => Get("Smell_Fix_ExtractSuperclass");

    /// <summary>Introduce Parameter Object</summary>
    public static string Smell_Fix_IntroduceParameterObject => Get("Smell_Fix_IntroduceParameterObject");

    /// <summary>Move Method</summary>
    public static string Smell_Fix_MoveMethod => Get("Smell_Fix_MoveMethod");

    /// <summary>Open in code viewer (Extract Method)</summary>
    public static string Smell_Fix_OpenViewer_ExtractMethod => Get("Smell_Fix_OpenViewer_ExtractMethod");

    /// <summary>Open in code viewer (Inline Method)</summary>
    public static string Smell_Fix_OpenViewer_InlineMethod => Get("Smell_Fix_OpenViewer_InlineMethod");

    /// <summary>Push Down Method</summary>
    public static string Smell_Fix_PushDownMethod => Get("Smell_Fix_PushDownMethod");

    /// <summary>Remove Setting Method</summary>
    public static string Smell_Fix_RemoveSettingMethod => Get("Smell_Fix_RemoveSettingMethod");

    /// <summary>Rename member</summary>
    public static string Smell_Fix_RenameMember => Get("Smell_Fix_RenameMember");

    /// <summary>Rename type</summary>
    public static string Smell_Fix_RenameType => Get("Smell_Fix_RenameType");

    /// <summary>Replace Data Value with Object</summary>
    public static string Smell_Fix_ReplaceDataValueWithObject => Get("Smell_Fix_ReplaceDataValueWithObject");

    /// <summary>Replace Type Code with Subclasses</summary>
    public static string Smell_Fix_ReplaceTypeCodeWithSubclasses => Get("Smell_Fix_ReplaceTypeCodeWithSubclasses");

    /// <summary>Ask AI</summary>
    public static string Smell_Popup_AskAiButton => Get("Smell_Popup_AskAiButton");

    /// <summary>AI analysis ({0}): {1} — no diff (explanation only)</summary>
    public static string Status_Ai_AnalysisOnly_Format => Get("Status_Ai_AnalysisOnly_Format");

    /// <summary>AI proposal diff apply failed ({0}): {1}</summary>
    public static string Status_Ai_ApplyFailed_Format => Get("Status_Ai_ApplyFailed_Format");

    /// <summary>AI consultation ({0}): cancelled or timeout ({1} min no response)</summary>
    public static string Status_Ai_Cancelled_Format => Get("Status_Ai_Cancelled_Format");

    /// <summary>AI consultation complete ({0}): {1}</summary>
    public static string Status_Ai_Completed_Format => Get("Status_Ai_Completed_Format");

    /// <summary>Asking AI ({0}): {1} @ {2}</summary>
    public static string Status_Ai_Consulting_Format => Get("Status_Ai_Consulting_Format");

    /// <summary>AI consultation error ({0}): {1} — {2}</summary>
    public static string Status_Ai_Error_Format => Get("Status_Ai_Error_Format");

    /// <summary>AI proposal (.cpp missing detected) — retrying ({0})</summary>
    public static string Status_Ai_FollowupInProgress_Format => Get("Status_Ai_FollowupInProgress_Format");

    /// <summary>AI consultation ({0}): failed to resolve CodeSmellViewModel</summary>
    public static string Status_Ai_SvmMissing_Format => Get("Status_Ai_SvmMissing_Format");

    /// <summary>⚠ Apply looks broken (type count {0} → {1}). Reloading solution…</summary>
    public static string Status_ApplyBroken_Reload_Format => Get("Status_ApplyBroken_Reload_Format");

    /// <summary>Applying {0} change(s)…</summary>
    public static string Status_ApplyingChanges => Get("Status_ApplyingChanges");

    /// <summary>Cannot change association on an external or ghost type.</summary>
    public static string Status_CantChangeAssociation => Get("Status_CantChangeAssociation");

    /// <summary>Cannot collapse an external or ghost type.</summary>
    public static string Status_CantCollapse => Get("Status_CantCollapse");

    /// <summary>Cannot convert constructor on an external or ghost type.</summary>
    public static string Status_CantConvertConstructor => Get("Status_CantConvertConstructor");

    /// <summary>Cannot convert to reference on an external or ghost type.</summary>
    public static string Status_CantConvertToReference => Get("Status_CantConvertToReference");

    /// <summary>Cannot encapsulate fields on an external or ghost type.</summary>
    public static string Status_CantEncapsulateField => Get("Status_CantEncapsulateField");

    /// <summary>Cannot extract class from an external or ghost type.</summary>
    public static string Status_CantExtractClass => Get("Status_CantExtractClass");

    /// <summary>Cannot extract a hierarchy from an external or ghost type.</summary>
    public static string Status_CantExtractHierarchy => Get("Status_CantExtractHierarchy");

    /// <summary>Cannot extract interface from an external or ghost type.</summary>
    public static string Status_CantExtractInterface => Get("Status_CantExtractInterface");

    /// <summary>Cannot extract superclass from an external or ghost type.</summary>
    public static string Status_CantExtractSuperclass => Get("Status_CantExtractSuperclass");

    /// <summary>Cannot flatten hierarchy on an external or ghost type.</summary>
    public static string Status_CantFlattenHierarchy => Get("Status_CantFlattenHierarchy");

    /// <summary>Cannot introduce a Null Object for an external or ghost type.</summary>
    public static string Status_CantIntroduceNullObject => Get("Status_CantIntroduceNullObject");

    /// <summary>Cannot introduce parameter object on an external or ghost type.</summary>
    public static string Status_CantIntroduceParamObj => Get("Status_CantIntroduceParamObj");

    /// <summary>Cannot lock down an external or ghost type.</summary>
    public static string Status_CantLockDown => Get("Status_CantLockDown");

    /// <summary>Cannot modify method signature on an external or ghost type.</summary>
    public static string Status_CantModifySignature => Get("Status_CantModifySignature");

    /// <summary>Cannot move fields from an external or ghost type.</summary>
    public static string Status_CantMoveFields => Get("Status_CantMoveFields");

    /// <summary>Cannot move methods from an external or ghost type.</summary>
    public static string Status_CantMoveMethods => Get("Status_CantMoveMethods");

    /// <summary>Cannot move procedures from an external or ghost type.</summary>
    public static string Status_CantMoveProcedures => Get("Status_CantMoveProcedures");

    /// <summary>Cannot preserve whole object on an external or ghost type.</summary>
    public static string Status_CantPreserveWholeObject => Get("Status_CantPreserveWholeObject");

    /// <summary>Cannot promote data value on an external or ghost type.</summary>
    public static string Status_CantPromoteDataValue => Get("Status_CantPromoteDataValue");

    /// <summary>Cannot pull up constructor body from an external or ghost type.</summary>
    public static string Status_CantPullUpConstructorBody => Get("Status_CantPullUpConstructorBody");

    /// <summary>Cannot pull up fields from an external or ghost type.</summary>
    public static string Status_CantPullUpFields => Get("Status_CantPullUpFields");

    /// <summary>Cannot pull up methods from an external or ghost type.</summary>
    public static string Status_CantPullUpMethods => Get("Status_CantPullUpMethods");

    /// <summary>Cannot push down fields from an external or ghost type.</summary>
    public static string Status_CantPushDownFields => Get("Status_CantPushDownFields");

    /// <summary>Cannot push down methods from an external or ghost type.</summary>
    public static string Status_CantPushDownMethods => Get("Status_CantPushDownMethods");

    /// <summary>Cannot remove setter from an external or ghost type.</summary>
    public static string Status_CantRemoveSetter => Get("Status_CantRemoveSetter");

    /// <summary>Cannot remove an external or ghost type.</summary>
    public static string Status_CantRemoveSubclass => Get("Status_CantRemoveSubclass");

    /// <summary>Cannot rename fields on an external or ghost type.</summary>
    public static string Status_CantRenameFields => Get("Status_CantRenameFields");

    /// <summary>Cannot rename members of an external or ghost type.</summary>
    public static string Status_CantRenameMembers => Get("Status_CantRenameMembers");

    /// <summary>Cannot rename parameter on an external or ghost type.</summary>
    public static string Status_CantRenameParameter => Get("Status_CantRenameParameter");

    /// <summary>Cannot replace array on an external or ghost type.</summary>
    public static string Status_CantReplaceArray => Get("Status_CantReplaceArray");

    /// <summary>Cannot replace magic numbers on an external or ghost type.</summary>
    public static string Status_CantReplaceMagicNumber => Get("Status_CantReplaceMagicNumber");

    /// <summary>Cannot replace type code on an external or ghost type.</summary>
    public static string Status_CantReplaceTypeCode => Get("Status_CantReplaceTypeCode");

    /// <summary>Cannot self-encapsulate on an external or ghost type.</summary>
    public static string Status_CantSelfEncapsulate => Get("Status_CantSelfEncapsulate");

    /// <summary>Cannot subclass an external or ghost type.</summary>
    public static string Status_CantSubclass => Get("Status_CantSubclass");

    /// <summary>Cannot tease apart an external or ghost type.</summary>
    public static string Status_CantTeaseApart => Get("Status_CantTeaseApart");

    /// <summary>External change detected — reloading…</summary>
    public static string Status_ExternalChangeReload => Get("Status_ExternalChangeReload");

    /// <summary>Failed: {0}</summary>
    public static string Status_Failed => Get("Status_Failed");

    /// <summary>Loading {0}…</summary>
    public static string Status_LoadingSln => Get("Status_LoadingSln");

    /// <summary>Load a member first.</summary>
    public static string Status_LoadMemberFirst => Get("Status_LoadMemberFirst");

    /// <summary>Name unchanged; nothing to do.</summary>
    public static string Status_NameUnchanged => Get("Status_NameUnchanged");

    /// <summary>Navigate failed: {0}</summary>
    public static string Status_NavigateFailed => Get("Status_NavigateFailed");

    /// <summary>{0} has no base type to fall back to. Remove Subclass requires a superclass.</summary>
    public static string Status_NoBaseForRemoveSubclass => Get("Status_NoBaseForRemoveSubclass");

    /// <summary>{0} has no base type to collapse into.</summary>
    public static string Status_NoBaseToCollapseInto => Get("Status_NoBaseToCollapseInto");

    /// <summary>{0} has no base type to pull up into.</summary>
    public static string Status_NoBaseToPullUp => Get("Status_NoBaseToPullUp");

    /// <summary>No changes were produced by the {0} proposal.</summary>
    public static string Status_NoChangesProduced => Get("Status_NoChangesProduced");

    /// <summary>No data record type available to move procedures onto.</summary>
    public static string Status_NoDataRecordAvailable => Get("Status_NoDataRecordAvailable");

    /// <summary>No other classes available as move target.</summary>
    public static string Status_NoOtherClassesAsMoveTarget => Get("Status_NoOtherClassesAsMoveTarget");

    /// <summary>No solution loaded.</summary>
    public static string Status_NoSolutionLoaded => Get("Status_NoSolutionLoaded");

    /// <summary>No solution loaded. Use File &gt; Open Solution… (Ctrl+O).</summary>
    public static string Status_NoSolutionLoadedHint => Get("Status_NoSolutionLoadedHint");

    /// <summary>{0} has no subclasses to fold in.</summary>
    public static string Status_NoSubclassesToFoldIn => Get("Status_NoSubclassesToFoldIn");

    /// <summary>{0} has no subclasses to push down into.</summary>
    public static string Status_NoSubclassesToPushDown => Get("Status_NoSubclassesToPushDown");

    /// <summary>No type node available for extract.</summary>
    public static string Status_NoTypeNodeExtract => Get("Status_NoTypeNodeExtract");

    /// <summary>No type node available for extract class.</summary>
    public static string Status_NoTypeNodeExtractClass => Get("Status_NoTypeNodeExtractClass");

    /// <summary>No type node available for extract superclass.</summary>
    public static string Status_NoTypeNodeExtractSuperclass => Get("Status_NoTypeNodeExtractSuperclass");

    /// <summary>No type node available for rename.</summary>
    public static string Status_NoTypeNodeRename => Get("Status_NoTypeNodeRename");

    /// <summary>Open a member in the code viewer first.</summary>
    public static string Status_OpenMemberFirst => Get("Status_OpenMemberFirst");

    /// <summary>{0} rejected.</summary>
    public static string Status_OperationRejected => Get("Status_OperationRejected");

    /// <summary>Proposal ready: {0} file change(s){1}</summary>
    public static string Status_ProposalReady => Get("Status_ProposalReady");

    /// <summary>Propose failed: {0}</summary>
    public static string Status_ProposeFailed => Get("Status_ProposeFailed");

    /// <summary>Proposing: {0}…</summary>
    public static string Status_Proposing => Get("Status_Proposing");

    /// <summary>Read failed: {0}</summary>
    public static string Status_ReadFailed => Get("Status_ReadFailed");

    /// <summary>Reference: {0}:{1}:{2}</summary>
    public static string Status_ReferenceLocation => Get("Status_ReferenceLocation");

    /// <summary>Ref target file missing: {0}</summary>
    public static string Status_RefTargetMissing => Get("Status_RefTargetMissing");

    /// <summary>Select the expression to extract in the code viewer first.</summary>
    public static string Status_SelectExprToExtract => Get("Status_SelectExprToExtract");

    /// <summary>Select the run of if-statements to consolidate.</summary>
    public static string Status_SelectIfRun => Get("Status_SelectIfRun");

    /// <summary>Select the statements to extract in the code viewer first.</summary>
    public static string Status_SelectStatementsToExtract => Get("Status_SelectStatementsToExtract");

    /// <summary>Showing {0}/{1} types (+{2} external), {3} relationships</summary>
    public static string Status_Showing => Get("Status_Showing");

    /// <summary>For "{0}": open the code viewer, select a range, then use the right-click refactoring menu.</summary>
    public static string Status_Smell_OpenViewerHint_Format => Get("Status_Smell_OpenViewerHint_Format");

    /// <summary>"{0}" is a type-level smell — open a member and try again.</summary>
    public static string Status_Smell_TypeLevelHint_Format => Get("Status_Smell_TypeLevelHint_Format");

    /// <summary>Solution not found: {0}</summary>
    public static string Status_SolutionNotFound => Get("Status_SolutionNotFound");

    /// <summary>Source not found for {0}</summary>
    public static string Status_SourceNotFoundFor => Get("Status_SourceNotFoundFor");

    /// <summary>Viewing {0}.{1}</summary>
    public static string Status_ViewingMember => Get("Status_ViewingMember");

    /// <summary>Delegation field name (added to primary root)</summary>
    public static string TeaseApartInheritance_DelegationField => Get("TeaseApartInheritance_DelegationField");

    /// <summary>Primary hierarchy root (gets a delegation field)</summary>
    public static string TeaseApartInheritance_PrimaryRoot => Get("TeaseApartInheritance_PrimaryRoot");

    /// <summary>Scaffold only — user pushes down / moves secondary-axis methods into the new subclasses afterwards, typically via Push Down Method.</summary>
    public static string TeaseApartInheritance_ScaffoldNote => Get("TeaseApartInheritance_ScaffoldNote");

    /// <summary>Secondary hierarchy name (new abstract root)</summary>
    public static string TeaseApartInheritance_SecondaryRoot => Get("TeaseApartInheritance_SecondaryRoot");

    /// <summary>Secondary subclass names (comma-separated)</summary>
    public static string TeaseApartInheritance_SecondarySubclassNames => Get("TeaseApartInheritance_SecondarySubclassNames");

    /// <summary>Tease apart inheritance</summary>
    public static string TeaseApartInheritance_Title => Get("TeaseApartInheritance_Title");

    /// <summary>Clear</summary>
    public static string Toolbar_Clear => Get("Toolbar_Clear");

    /// <summary>Clear diff</summary>
    public static string Toolbar_DiffOverlay_Clear => Get("Toolbar_DiffOverlay_Clear");

    /// <summary>Clear</summary>
    public static string Toolbar_ImpactFocus_Clear => Get("Toolbar_ImpactFocus_Clear");

    /// <summary>+1 hop</summary>
    public static string Toolbar_ImpactFocus_ExpandOneHop => Get("Toolbar_ImpactFocus_ExpandOneHop");

    /// <summary>Namespace</summary>
    public static string Toolbar_Namespace => Get("Toolbar_Namespace");

    /// <summary>Search</summary>
    public static string Toolbar_Search => Get("Toolbar_Search");
}
