using Kata.Core.Model;
using Kata.Roslyn;

namespace Kata.Tests;

public sealed class CSharpLanguageAdapterTests
{
    [Fact]
    public async Task Loads_Kata_solution_and_maps_projects()
    {
        var slnPath = SolutionRoot.GetKataSolutionPath();
        var adapter = new CSharpLanguageAdapter();

        var model = await adapter.LoadSolutionAsync(slnPath);

        Assert.Equal(slnPath, model.FilePath);
        Assert.Contains(model.Projects, p => p.Name == "Kata.Core");
        Assert.Contains(model.Projects, p => p.Name == "Kata.Roslyn");
    }

    [Fact]
    public async Task Kata_Core_contains_expected_domain_types()
    {
        var slnPath = SolutionRoot.GetKataSolutionPath();
        var adapter = new CSharpLanguageAdapter();

        var model = await adapter.LoadSolutionAsync(slnPath);
        var core = model.Projects.Single(p => p.Name == "Kata.Core");

        Assert.Contains(core.Types, t => t.Name == "TypeRef" && t.Namespace.FullName == "Kata.Core.Model");
        Assert.Contains(core.Types, t => t.Name == "RefactoringIntent" && t.Namespace.FullName == "Kata.Core.Intents");
        Assert.Contains(core.Types, t => t.Name == "ILanguageAdapter" && t.Kind == TypeKind.Interface);
    }

    [Fact]
    public async Task RenameIntent_has_NewName_property_visible_in_members()
    {
        var slnPath = SolutionRoot.GetKataSolutionPath();
        var adapter = new CSharpLanguageAdapter();

        var model = await adapter.LoadSolutionAsync(slnPath);
        var renameIntent = model.Projects
            .Single(p => p.Name == "Kata.Core")
            .Types
            .Single(t => t.Name == "RenameIntent");

        Assert.Contains(renameIntent.Members, m => m.Name == "NewName" && m.Kind == MemberKind.Property);
    }

    [Fact]
    public async Task Intent_hierarchy_produces_base_type_edges()
    {
        var slnPath = SolutionRoot.GetKataSolutionPath();
        var adapter = new CSharpLanguageAdapter();

        var model = await adapter.LoadSolutionAsync(slnPath);
        var core = model.Projects.Single(p => p.Name == "Kata.Core");
        var renameIntent = core.Types.Single(t => t.Name == "RenameIntent");

        Assert.Contains(
            renameIntent.BaseTypes,
            tr => tr.FullyQualifiedName.EndsWith("RefactoringIntent"));
    }

    [Fact]
    public async Task CSharpLanguageAdapter_reports_ILanguageAdapter_as_interface()
    {
        var slnPath = SolutionRoot.GetKataSolutionPath();
        var adapter = new CSharpLanguageAdapter();

        var model = await adapter.LoadSolutionAsync(slnPath);
        var roslyn = model.Projects.Single(p => p.Name == "Kata.Roslyn");
        var csharpAdapter = roslyn.Types.Single(t => t.Name == "CSharpLanguageAdapter");

        Assert.Contains(
            csharpAdapter.ImplementedInterfaces,
            tr => tr.FullyQualifiedName.EndsWith("ILanguageAdapter"));
    }

    [Fact]
    public async Task SDK_generated_test_entrypoint_is_filtered_out()
    {
        var slnPath = SolutionRoot.GetKataSolutionPath();
        var adapter = new CSharpLanguageAdapter();

        var model = await adapter.LoadSolutionAsync(slnPath);
        var allTypeNames = model.Projects.SelectMany(p => p.Types.Select(t => t.Name)).ToArray();

        Assert.DoesNotContain("AutoGeneratedProgram", allTypeNames);
    }

    [Fact]
    public async Task Top_level_statement_Program_class_is_retained()
    {
        var slnPath = SolutionRoot.GetKataSolutionPath();
        var adapter = new CSharpLanguageAdapter();

        var model = await adapter.LoadSolutionAsync(slnPath);
        var mcp = model.Projects.Single(p => p.Name == "Kata.Mcp");

        Assert.Contains(mcp.Types, t => t.Name == "Program");
    }

    [Fact]
    public async Task Handwritten_WPF_partial_types_remain()
    {
        var slnPath = SolutionRoot.GetKataSolutionPath();
        var adapter = new CSharpLanguageAdapter();

        var model = await adapter.LoadSolutionAsync(slnPath);
        var app = model.Projects.Single(p => p.Name == "Kata.App");

        Assert.Contains(app.Types, t => t.Name == "App");
        Assert.Contains(app.Types, t => t.Name == "MainWindow");
    }
}
