<#
.SYNOPSIS
    Localization/Strings.resx から Strings.Designer.cs を作り直す。

.DESCRIPTION
    .NET SDK には resx を C# に起こす仕組みが無く (Visual Studio のカスタムツール
    PublicResXFileCodeGenerator は IDE 前提)、CLI だけでビルドできる状態を保ちたいので
    生成をここで賄う。生成物はコミットする。

    表示文字列を足したら resx を編集してこれを実行すること。

.EXAMPLE
    pwsh tools/Generate-Strings.ps1
#>
[CmdletBinding()]
param(
    [string]$ResxPath,
    [string]$OutputPath
)

$ErrorActionPreference = 'Stop'

# WinPS 5.1 では param のデフォルト式に $PSScriptRoot を書くと解決前に評価されて空になる。
# 本体で決めれば -File 起動でも Get-Content -Raw でも同じ挙動になる
if (-not $ResxPath)   { $ResxPath   = Join-Path $PSScriptRoot '..\src\Kata.App\Localization\Strings.resx' }
if (-not $OutputPath) { $OutputPath = Join-Path $PSScriptRoot '..\src\Kata.App\Localization\Strings.Designer.cs' }

[xml]$resx = Get-Content -Path $ResxPath -Raw -Encoding UTF8

$entries = @()
foreach ($node in $resx.root.data) {
    if (-not $node.name) { continue }
    $entries += [pscustomobject]@{
        Name  = $node.name
        Value = [string]$node.value
    }
}
$entries = $entries | Sort-Object Name

if ($entries.Count -eq 0) { throw "no <data> entries found in $ResxPath" }

$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine('// <auto-generated>')
[void]$sb.AppendLine('//     tools/Generate-Strings.ps1 が Strings.resx から生成している。')
[void]$sb.AppendLine('//     直接編集しても次の生成で消える。文字列を足すときは resx を直して再生成すること。')
[void]$sb.AppendLine('// </auto-generated>')
[void]$sb.AppendLine('#nullable enable')
[void]$sb.AppendLine('using System.Globalization;')
[void]$sb.AppendLine('using System.Resources;')
[void]$sb.AppendLine()
[void]$sb.AppendLine('namespace Kata.App.Localization;')
[void]$sb.AppendLine()
[void]$sb.AppendLine('/// <summary>画面に出す文字列。実際の言語は起動時の CurrentUICulture で決まる。</summary>')
[void]$sb.AppendLine('public static class Strings')
[void]$sb.AppendLine('{')
[void]$sb.AppendLine('    public static ResourceManager ResourceManager { get; } =')
[void]$sb.AppendLine('        new("Kata.App.Localization.Strings", typeof(Strings).Assembly);')
[void]$sb.AppendLine()
[void]$sb.AppendLine('    private static string Get(string key)')
[void]$sb.AppendLine('        => ResourceManager.GetString(key, CultureInfo.CurrentUICulture) ?? key;')

foreach ($e in $entries) {
    $doc = $e.Value -replace '&', '&amp;' -replace '<', '&lt;' -replace '>', '&gt;'
    $doc = ($doc -split "`r?`n") -join ' '
    [void]$sb.AppendLine()
    [void]$sb.AppendLine("    /// <summary>$doc</summary>")
    [void]$sb.AppendLine("    public static string $($e.Name) => Get(`"$($e.Name)`");")
}

[void]$sb.AppendLine('}')

$utf8 = New-Object System.Text.UTF8Encoding $false
[System.IO.File]::WriteAllText($OutputPath, $sb.ToString(), $utf8)

Write-Host "generated $($entries.Count) strings -> $OutputPath"
